### ISSUE TITLE
アクセストークンを取得できない

### ISSUE THREAD

**Issue by yuta0801** [codic-project/README#2]
サイト上を探したのですが問い合わせ先が見つからなかったのでここに失礼します

エディタのプラグインからcodicを使用したく、説明にそってサインアップ後以下のリンクを開いたのですが、何も表示されません。左上にあるDASHBOARDなども押してみましたが反応はありませんでした。
<https://codic.jp/my/api_status>
![image](https://user-images.githubusercontent.com/21266306/39660621-9fb02788-5075-11e8-950c-f5c07f4a6044.png)

**Comment by kenji-namba** [comment]
お問い合わせありがとうございます。

もし、デバッグツールなどでJavaScriptエラーなどが出ていましたら、教えていただけますでしょうか。
また、ご利用のブラウザも教えてください。

**Comment by yuta0801** [comment]
コンソールを確認するために同じ環境で再度同じページを開いたら正しく表示されました。
原因はわかりませんが、対応ありがとうございました。

**Comment by kenji-namba** [comment]
おそらく、キャッシュとかですかね...
解決されたという事でこちらのissueはクローズさせていただきますね。
こちらこそありがとうございました。
